<div id="foot-row" class="collapsed">
  <div class="foot-row-cont">
    <span id="copyright">&copy; 依波路 &#183; 版權所有 &#183; 不得轉載</span>    
    <div class="yui3-g">
      <div class="yui3-u-1-2">
        <h4>最新產品</h4>
        <div class="content">
          <div class="yui3-g">
            <div class="yui3-u-1-3">
              <div class="content">
                <h5>
                  <a href="wristwatch/couple/" title="浪漫情侶">浪漫情侶</a>
                </h5>
                <ul class="sub-indent">
                  <%=couple %>
                </ul>
              </div>
            </div>
            <div class="yui3-u-1-3">
              <div class="content">
                <h5>
                  <a href="wristwatch/lady/" title="優雅淑女">優雅淑女</a>
                </h5>
                <ul class="sub-indent">
                  <%=lady %>
                </ul>
              </div>
            </div>
            <div class="yui3-u-1-3">
              <div class="content">
                <h5>
                  <a href="wristwatch/casual/" title="瀟灑雅仕">瀟灑雅仕</a>
                </h5>
                <ul class="sub-indent">
                  <%=casual %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="yui3-u-1-4">
        <div class="content">
          <h4><a href="wristwatch_catalogue" class="title" title="產品目錄">產品目錄</a></h4>
          <h4>技術信息</h4>
          <ul>
            <li>
              <a href="tech_info_terminology" title="手表類型及常用術語">手表類型及常用術語</a>
            </li>
            <li>
              <a href="tech_info_instruction" title="手表使用須知">手表使用須知</a>
            </li>
          </ul>
          <h4>搜尋</h4>
          <ul>
            <li>
              <a href="wristwatch_selector" title="選擇器">選擇器</a>
            </li>
          </ul>
          <h4>品牌</h4>
          <ul>
            <li>
              <a href="brand_history/" title="品牌歷史">品牌歷史</a>
            </li>
          </ul>

          <h4>依波路世界</h4>
          <ul>
            <li>
              <a href="newspage" title="企業新聞">企業新聞</a>
            </li>
            <li>
              <a href="download_app/" title="手機應用程式">手機應用程式</a>
            </li>
            <li>
              <a href="download_wallpaper/" title="壁紙">壁紙</a>
            </li>
            <li>
              <a href="download_screensaver/" title="屏幕保護程式">屏幕保護程式</a>
            </li>
            <li>
              <a id="social_network/" href="social_network" title="照片分享">照片分享</a>
            </li>
          </ul>

          
          
        </div>
      </div>

      <div class="yui3-u-1-4">

        <div class="content">
          
          <h4><a href="cs_store" class="title">客戶服務</a></h4>
          
          <h4>投資者關係</h4>
          <ul>
            <li>
              <a href="investor_listing" title="上市文件">上市文件</a>
            </li>
            <li>
              <a href="investor_announcement" title="公告">公告</a>
            </li>
            <li>
              <a href="investor_report" title="財務報告">財務報告</a>
            </li>
            <li>
              <a href="investor_enquiry" title="投資者查詢">投資者查詢</a>
            </li>
			<li>
              <a href="investor_inspection" title="展示文件">展示文件</a>
            </li>
          </ul>

          <h4><a href="legalNcopyright.aspx" class="title">法律與版權聲明</a></h4>
          

          <h4>聯絡我們</h4>
          <ul>
            <li>
              <a href="mailto:info@ernestborel.ch" title="Ernest Borel S.A. (Head Office)">Ernest Borel S.A. (Head Office)<br>Rue des Perrières 8, Case postale 234, CH – 2340 Le Noirmont, Switzerland<br>T: +41-32-926 1726</a>
            </li><br>
            <li>
              <a href="mailto:Enquiry@ernestborel.ch" title="Ernest Borel (Far Est) Co. Ltd">依波路 (遠東) 有限公司<br>香港九龍旺角太子道西193號新世紀廣場第一座16樓1612-18室<br>電話: (852) 3628 5511</a>
            </li><br>
            <li>
              <a href="mailto:Enquiry@ernestborel.ch" title="Ernest Borel (Guangzhou) Co., Ltd">依波路 (廣州) 貿易有限公司<br>廣州市天河區天河路385號太古匯一座701室<br>電話: 400 830 3865 / 800 830 3865</a>
            </li>
          </ul>

        </div>        
      </div>
    </div>
  </div>
</div>

<!--
<div id="footer">
  <footer>
    <a href="legalNcopyright.aspx">法律與版權聲明</a>
    <span class="copyright">2011 &copy; 依波路 &#183; 版權所有 &#183; 不得轉載</span>
  </footer>
</div>
-->