<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?v=2">
<link rel="stylesheet" href="/css/style.css?v=202008">
<div id="header">
	<header>
		<a href="/tc/" class="logoLink"><img src="/images/trans.gif" width="140" height="121" title="依波路 - 1856" alt="依波路"></a>
		<div id="panelBar">
			<!--
			<a href="tech_info_terminology/" class="icon2" id="icon-technical" title="技術信息"><img src="images/icon_tech.png" alt='技術信息'></a>
			<a href="download/" class="icon2" id="icon-download" title="下載"><img src="images/icon_download.png" alt="下載"></a>
			<a href="javascript:void(0);" class="icon" id="icon-search" rel="search" title="搜尋">搜尋</a>
			-->
			<a class="icon pic" id="icon-weibo" rel="weibo" title="瑞士依波路表中國官方微博" href="http://www.weibo.com/ernestborel" target="_blank">微博</a>
			<a class="icon pic" id="icon-wechat" rel="wechat" title="微信" href="javascript:void(0);" target="_blank">微信</a>
			<a class="icon pic" id="icon-instagram" rel="instagram" title="Instagram" href="https://instagram.com/explore/tags/ernestborel/" target="_blank">Instagram</a>
			<a class="icon pic" id="icon-twitter" rel="twitter" title="Twitter" href="https://twitter.com/hashtag/ernestborel" target="_blank">Twitter</a>
			<a class="icon pic" id="icon-youtube" rel="youtube" title="YouTube" href="https://www.youtube.com/channel/UCpBRNkl6JCDp308kSVR1Ulw" target="_blank">YouTube</a>
			<a class="icon pic" id="icon-facebook" rel="facebook" title="Facebook專頁" href="https://www.facebook.com/ErnestBorelHK" target="_blank">Facebook</a>
			<a class="icon" id="icon-lang" rel="language" title="更改語言" href="javascript:void(0);">更改語言</a>
		</div>
	</header>
	<div id="wechat-qrcode"><img src="/images/sns_icon/wechat_qr_code.png"></div>
</div>