<div id="nav" class="ch">
	<nav>
		<ul>
			<li class="n0 nav"><a href="/tc/">主頁 </a></li>
			<li class="n1 nav haveSub">
				<a href="wristwatch">產品 <span class="nav_arrow">&#x25bc;</span></a>
				<ul class="sub-navCtnr">
					<li data-p="n1"><a href="wristwatch/" class="subCateName">系列</a></li>
					<li data-p="n1"><a href="wristwatch_catalogue" class="subCateName">產品目錄</a></li>
					<li data-p="n1"><a href="tech_info_terminology/" class="subCateName">技術信息</a></li>
					<li data-p="n1"><a href="wristwatch_selector/" class="subCateName">搜尋</a></li>
				</ul>
			</li>
			<li class="n2 nav">
				<a href="brand_history/">品牌 </a>
			</li>
			<li class="n3 nav haveSub">
				<a href="newspage/">依波路世界 <span class="nav_arrow">&#x25bc;</span></a>
				<ul class="sub-navCtnr">
					<li data-p="n3"><a href="newspage" class="subCateName">企業新聞</a></li>
					<li data-p="n3"><a href="ambassador/" class="subCateName">品牌代言人</a></li>
					<li data-p="n3"><a href="download_app/" class="subCateName">手機應用程式</a></li>
					<li data-p="n3"><a href="download_wallpaper/" class="subCateName">壁紙</a></li>
					<li data-p="n3"><a href="download_screensaver/" class="subCateName">屏幕保護程式</a></li>
					<!-- <li data-p="n3"><a href="social_network/" class="subCateName">照片分享</a></li> -->
				</ul>
			</li>
			<li class="n4 nav">
				<a href="cs_store/">零售點 </a>
			</li>
			<li class="n5 nav">
				<a href="cs_aftersales/">售後服務點 </a>
			</li>
			<li class="n6 nav haveSub">
				<a href="investor/">投資者關係 <span class="nav_arrow">&#x25bc;</span></a>
				<ul class="sub-navCtnr">
					<li data-p="n6"><a href="investor_corporate_info/" class="subCateName">公司資料</a></li>
					<li data-p="n6"><a href="investor_listing/" class="subCateName">上市文件</a></li>
					<li data-p="n6"><a href="investor_announcement/" class="subCateName">公告</a></li>
					<li data-p="n6"><a href="investor_report/" class="subCateName">財務報告</a></li>
					<li data-p="n6"><a href="investor_enquiry/" class="subCateName">投資者查詢</a></li>
					<li data-p="n6"><a href="investor_inspection/" class="subCateName">展示文件</a></li>
				</ul>
			</li>
			<!-- <li class="n7 nav">
				<a href="wristwatch_warranty">網上保修登記</a>
			</li> -->
		</ul>
		<div class="navGrad"></div>
	</nav>
</div>
