<div id="foot-row" class="collapsed">
  <div class="foot-row-cont">
    <span id="copyright">法律＆著作権</span>
    <a href="javascript:footerExpandBtnClick();" title="expand" id="icon-footrow-expand" class="icon btnShowHide">詳細 &#9660;</a>
    <a href="javascript:footerExpandBtnClick();" title="expand" id="icon-footrow-hide" class="icon btnShowHide hideBtn">隠す &#9650;</a>
    <div class="yui3-g">
      <div class="yui3-u-1-2 canHide">
        <h4>最新製品</h4>
        <div class="content">
          <div class="yui3-g">
            <div class="yui3-u-1-3">
              <div class="content">
                <h5>
                  <a href="wristwatch/couple/" title="ROMANTIC SERIES">ROMANTIC SERIES</a>
                </h5>
                <ul class="sub-indent">
                  <%=couple %>
                </ul>
              </div>
            </div>
            <div class="yui3-u-1-3">
              <div class="content">
                <h5>
                  <a href="wristwatch/lady/" title="FEMININE SERIES">FEMININE SERIES</a>
                </h5>
                <ul class="sub-indent">
                  <%=lady %>
                </ul>
              </div>
            </div>
            <div class="yui3-u-1-3">
              <div class="content">
                <h5>
                  <a href="wristwatch/casual/" title="CASUAL SERIES">CASUAL SERIES</a>
                </h5>
                <ul class="sub-indent">
                  <%=casual %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="yui3-u-1-4 canHide">
        <div class="content">
          <h4>
            <a href="wristwatch_catalogue" class="title" title="カタログ">カタログ</a>
          </h4>
          <h4>技術情報 </h4>
          <ul>
            <li>
              <a href="tech_info_terminology" title="專門用語">專門用語</a>
            </li>
            <li>
              <a href="tech_info_instruction" title="取扱說明書">取扱說明書</a>
            </li>
          </ul>
          <h4>検索する</h4>
          <ul>
            <li>
              <a href="wristwatch_selector" title="セレクター">セレクター</a>
            </li>
          </ul>
          <h4>ブランド</h4>
          <ul>
            <li>
              <a href="brand_history/" title="ブランド歴史文化">ブランド歴史文化</a>
            </li>
          </ul>

          <h4>依波路世界</h4>
          <ul>
            <li>
              <a href="newspage" title="企業情報">企業情報</a>
            </li>
            <li>
              <a href="download_app/" title="モバイルアプリケーション">モバイルアプリケーション</a>
            </li>
            <li>
              <a href="download_wallpaper/" title="壁紙">壁紙</a>
            </li>
            <li>
              <a href="download_screensaver/" title="スクリーンセーバー">スクリーンセーバー</a>
            </li>
            <li>
              <a id="social_network/" href="social_network" title="照片分享">照片分享</a>
            </li>
          </ul>



        </div>
      </div>

      <div class="yui3-u-1-4 canHide">

        <div class="content">

          <h4>
            <a href="cs_store" class="title">カスタマーサービス</a>
          </h4>

          <h4>
            <a href="legalNcopyright.aspx" class="title">法律＆著作権</a>
          </h4>


          <h4>お問い合わせ</h4>
           <ul>
            <li>
              <a href="mailto:info@ernestborel.ch" title="Ernest Borel S.A. (Head Office)">Ernest Borel S.A. (Head Office)<br>Rue des Perrières 8, Case postale 234, CH – 2340 Le Noirmont, Switzerland<br>T: +41-32-926 1726</a>
            </li><br>
            <li>
              <a href="mailto:Enquiry@ernestborel.ch" title="Ernest Borel (Far Est) Co. Ltd">Ernest Borel (Far East) Co., Ltd<br>Units 1612-18, Level 16, Tower I, Grand Century Place, 193 Prince Edward Road West, Mong Kok, Kowloon, Hong Kong<br>T: (852) 3628 5511</a>
            </li><br>
            <li>
              <a href="mailto:Enquiry@ernestborel.ch" title="Ernest Borel (Guangzhou) Co., Ltd">Ernest Borel (Guangzhou) Co., Ltd<br>Suite 701, Taikoo Hui Tower 1, 385 Tianhe Road, Tianhe District, Guangzhou 510620, China<br>T: 400 830 3865 / 800 830 3865</a>
            </li>
          </ul>

        </div>
      </div>
    </div>
  </div>
</div>

<!--
<div id="footer">
  <footer>
    <a href="legalNcopyright.aspx">法律与版权声明</a>
    <span class="copyright">2011 &copy; 依波路 &#183; 版权所有 &#183; 不得转载</span>
  </footer>
</div>
-->