<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?v=2">
<link rel="stylesheet" href="/css/style.css?v=201810">
<div id="header">
	<header>
		<a href="/jp/" class="logoLink"><img src="/images/trans.gif" width="140" height="121" title="Ernest Borel - 1856" alt="Ernest Borel"></a>
		<div id="panelBar">
			<!--
			<a href="tech_info_terminology/" class="icon2" id="icon-technical" title="技術情報"><img src="../images/icon_tech.png" alt='技術情報'></a>
			<a href="download/" class="icon2" id="icon-download" title="ダウンロード"><img src="../images/icon_download.png" alt="ダウンロード"></a>
			<a href="javascript:void(0);" class="icon" id="icon-search" rel="search" title="検索">検索</a>
			-->
			<a class="icon pic" id="icon-weibo" rel="weibo" title="weibo" href="http://www.weibo.com/ernestborel" target="_blank">weibo</a>
      <a class="icon pic" id="icon-wechat" rel="wechat" title="wechat" href="javascript:void(0);" target="_blank">wechat</a>
      <a class="icon pic" id="icon-instagram" rel="instagram" title="Instagram" href="https://instagram.com/explore/tags/ernestborel/" target="_blank">Instagram</a>
      <a class="icon pic" id="icon-twitter" rel="twitter" title="Twitter" href="https://twitter.com/hashtag/ernestborel" target="_blank">Twitter</a>
      <a class="icon pic" id="icon-youtube" rel="youtube" title="YouTube" href="https://www.youtube.com/channel/UCpBRNkl6JCDp308kSVR1Ulw" target="_blank">YouTube</a>
      <a class="icon pic" id="icon-facebook" rel="facebook" title="Facebook專頁" href="https://www.facebook.com/ErnestBorelHK" target="_blank">Facebook</a>
      <a class="icon" id="icon-lang" rel="language" title="言語" href="javascript:void(0);">言語</a>
		</div>
	</header>
</div>