<div id="nav" class="ch">
  <nav>
    <ul>
      <li class="n0 nav">
        <a href="/jp/">メインページ </a>
      </li>
      <li class="n1 nav haveSub">
        <a href="wristwatch"> 製品 <span class="nav_arrow">&#x25bc;</span> </a>
        <ul class="sub-navCtnr">
          <li data-p="n1"> <a href="wristwatch/" class="subCateName">コレクション</a> </li>
          <li data-p="n1"> <a href="wristwatch_catalogue" class="subCateName">カタログ</a> </li>
          <li data-p="n1"> <a href="tech_info_terminology/" class="subCateName">技術情報</a> </li>
          <li data-p="n1"> <a href="wristwatch_selector/" class="subCateName"> 検索する</a> </li>
        </ul>
      </li>
      <li class="n2 nav">
        <a href="brand_history/"> ブランド  </a>
        <!--
        <ul class="sub-navCtnr">
          <li data-p="n2"> <a href="brand_history/" class="subCateName">ブランドの歴史</a> </li>
          <li class="haveSub2" data-p="n2" data-s="ss0"> <a href="ambassador_raymond/" class="subCateName">アンバサダー</a>
          <li data-p="n2" data-s="ss0"> <a href="ambassador_raymond/" class="subCateName">アンバサダー</a> 
            <ul class="n2-ss0 sub-sub-navCtnr">
              <li> <a href="ambassador_raymond/" class="subCateName">レイモンド・ラム</a> </li>
              <li> <a href="ambassador_kelly/" class="subCateName">ケリー・チャン</a> </li>
            </ul>
          </li>
        </ul>
         -->
      </li>
      <li class="n3 nav haveSub">
        <a href="newspage/"> 依波路世界 <span class="nav_arrow">&#x25bc;</span> </a>
        <ul class="sub-navCtnr">
          <li data-p="n3"> <a href="newspage" class="subCateName">企業情報</a> </li>
		  <li data-p="n3"><a href="ambassador/" class="subCateName">製品のイメージモデル</a></li>
          <li data-p="n3"> <a href="download_app/" class="subCateName">モバイルアプリケーション</a> </li>
          <li data-p="n3"> <a href="download_wallpaper/" class="subCateName">壁紙</a> </li>
          <li data-p="n3"> <a href="download_screensaver/" class="subCateName">スクリーンセーバー</a> </li>
          <!-- <li data-p="n3"> <a href="social_network/" class="subCateName">写真共有</a> </li> -->
        </ul>
      </li>
      <li class="n4 nav">
        <a href="cs_store/">販売会社</a>
      </li>
      <li class="n5 nav">
        <a href="cs_aftersales/">サービスサイト</a>
      </li>
    </ul>
    <div class="navGrad"></div>
  </nav>
</div>