<div class="panel language ">
	<div class="inner-panel" id="slidePan">
		<span class="title">更改语言</span>
		<span class="currentLang">日本語</span> |
		<a class="langLink jp" href="<%=domain_cn %>/">简体中文</a><span class="sc"> | </span>
		<a class="langLink tc" href="<%=domain_ch %>/tc/">繁體中文</a><span class="tc"> | </span>
		<a class="langLink en" href="<%=domain_ch %>/en/">ENGLISH</a><span class="en"> | </span>
	</div>
</div>
