<link rel="stylesheet" type="text/css" href="/css/reset-fonts-grids.css">
<link rel="stylesheet" type="text/css" href="/css/colorbox.css">
<link rel="stylesheet" type="text/css" href="/css/magnific-popup.css"> 
<link rel="stylesheet" type="text/css" href="/css/select2.css">
<link rel="stylesheet" type="text/css" href="/css/pagination.css">
<link rel="stylesheet" type="text/css" href="/css/style.css?v=212878">
<link rel="stylesheet" type="text/css" href="/css/style_ch.css?v=2">
<script type="text/javascript" src="/js/jquery/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="/js/jquery/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="/js/jquery/jquery.color.js"></script>
<script type="text/javascript" src="/js/jquery.colorbox-min.js"></script>
<script type="text/javascript" src="/js/jquery/jquery.cycle.all.min.js"></script>
<script type="text/javascript" src="/js/jquery/jquery.magnific-popup.min.js"></script>
<script type="text/javascript" src="/js/jquery/jquery.jwplayer.js"></script>
<script type="text/javascript" src="/js/jquery/jquery.pagination.js"></script>
<script type="text/javascript" src="/js/jquery/jquery.ellipsis.js"></script>
<script type="text/javascript" src="/js/cycle.with.progressbar.js"></script>
<script type="text/javascript" src="/js/jwplayer.js"></script>
<script type="text/javascript" src="/js/galleryslider.js"></script>
<script type="text/javascript" src="/js/greensock-js/TweenMax.min.js"></script>
<script type="text/javascript" src="/js/greensock-js/easing/EasePack.min.js"></script>
<script type="text/javascript" src="/js/greensock-js/plugins/CSSPlugin.min.js"></script>
<script type="text/javascript" src="/js/select2.js"></script>
<script type="text/javascript" src="/js/uifn.js?v=2" ></script>