//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErnestBorel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErnestBorel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string bc_home_en {
            get {
                return ResourceManager.GetString("bc_home_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string bc_home_fr {
            get {
                return ResourceManager.GetString("bc_home_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メインページ.
        /// </summary>
        public static string bc_home_jp {
            get {
                return ResourceManager.GetString("bc_home_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主页.
        /// </summary>
        public static string bc_home_sc {
            get {
                return ResourceManager.GetString("bc_home_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 依波路.
        /// </summary>
        public static string bc_home_tc {
            get {
                return ResourceManager.GetString("bc_home_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string bc_watch_en {
            get {
                return ResourceManager.GetString("bc_watch_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string bc_watch_fr {
            get {
                return ResourceManager.GetString("bc_watch_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新製品.
        /// </summary>
        public static string bc_watch_jp {
            get {
                return ResourceManager.GetString("bc_watch_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新产品.
        /// </summary>
        public static string bc_watch_sc {
            get {
                return ResourceManager.GetString("bc_watch_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新產品.
        /// </summary>
        public static string bc_watch_tc {
            get {
                return ResourceManager.GetString("bc_watch_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance in Heart Since 1856. Ernest Borel –  founded in Neuchatel, Switzerland. Exquisitely elegant, admirably designed automatic and quartz-movement wrist watches for men and women..
        /// </summary>
        public static string collection_desc_all_en {
            get {
                return ResourceManager.GetString("collection_desc_all_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance in Heart Since 1856. Ernest Borel –  founded in Neuchatel, Switzerland. Exquisitely elegant, admirably designed automatic and quartz-movement wrist watches for men and women..
        /// </summary>
        public static string collection_desc_all_fr {
            get {
                return ResourceManager.GetString("collection_desc_all_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance in Heart Since 1856. Ernest Borel –  founded in Neuchatel, Switzerland. Exquisitely elegant, admirably designed automatic and quartz-movement wrist watches for men and women..
        /// </summary>
        public static string collection_desc_all_jp {
            get {
                return ResourceManager.GetString("collection_desc_all_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 瑞士手表品牌—依波路，推出最新高档手表产品包括自动系列和石英系列，分别为男士、女士分别打造不同品味的高档手表,情侣表等.
        /// </summary>
        public static string collection_desc_all_sc {
            get {
                return ResourceManager.GetString("collection_desc_all_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 源自1856年的浪漫經典 — 依波路，發源自「鐘表王國」瑞士紐察圖，以&apos;精益求精&apos;的探索精神，打造出款式設計典雅精致的奢華腕表。.
        /// </summary>
        public static string collection_desc_all_tc {
            get {
                return ResourceManager.GetString("collection_desc_all_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel {0} Collection : {1}.
        /// </summary>
        public static string collection_desc_type_en {
            get {
                return ResourceManager.GetString("collection_desc_type_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel {0} Collection : {1}.
        /// </summary>
        public static string collection_desc_type_fr {
            get {
                return ResourceManager.GetString("collection_desc_type_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - {0} : {1}.
        /// </summary>
        public static string collection_desc_type_jp {
            get {
                return ResourceManager.GetString("collection_desc_type_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 瑞士手表品牌依波路手表，推出最新{0}名牌手表包括{1}.
        /// </summary>
        public static string collection_desc_type_sc {
            get {
                return ResourceManager.GetString("collection_desc_type_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 瑞士手表品牌依波路手表，推出最新{0}名牌手表包括{1}.
        /// </summary>
        public static string collection_desc_type_tc {
            get {
                return ResourceManager.GetString("collection_desc_type_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - Watch Collections.
        /// </summary>
        public static string collection_title_all_en {
            get {
                return ResourceManager.GetString("collection_title_all_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - Watch Collections.
        /// </summary>
        public static string collection_title_all_fr {
            get {
                return ResourceManager.GetString("collection_title_all_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - 最新製品.
        /// </summary>
        public static string collection_title_all_jp {
            get {
                return ResourceManager.GetString("collection_title_all_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 依波路官方网站 - 依波路手表最新产品.
        /// </summary>
        public static string collection_title_all_sc {
            get {
                return ResourceManager.GetString("collection_title_all_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 依波路官方網站 - 依波路手表最新產品.
        /// </summary>
        public static string collection_title_all_tc {
            get {
                return ResourceManager.GetString("collection_title_all_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - Watch Collections - {0}.
        /// </summary>
        public static string collection_title_type_en {
            get {
                return ResourceManager.GetString("collection_title_type_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - Watch Collections - {0}.
        /// </summary>
        public static string collection_title_type_fr {
            get {
                return ResourceManager.GetString("collection_title_type_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - 最新製品 - {0}.
        /// </summary>
        public static string collection_title_type_jp {
            get {
                return ResourceManager.GetString("collection_title_type_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 依波路表官方网站 - 依波路{0}手表.
        /// </summary>
        public static string collection_title_type_sc {
            get {
                return ResourceManager.GetString("collection_title_type_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 依波路表官方網站 - 依波路{0}手表.
        /// </summary>
        public static string collection_title_type_tc {
            get {
                return ResourceManager.GetString("collection_title_type_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - {0}.
        /// </summary>
        public static string title_en {
            get {
                return ResourceManager.GetString("title_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - {0}.
        /// </summary>
        public static string title_fr {
            get {
                return ResourceManager.GetString("title_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - {0}.
        /// </summary>
        public static string title_jp {
            get {
                return ResourceManager.GetString("title_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 瑞士依波路表官网 - {0}.
        /// </summary>
        public static string title_sc {
            get {
                return ResourceManager.GetString("title_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 瑞士依波路表官網 - {0}.
        /// </summary>
        public static string title_tc {
            get {
                return ResourceManager.GetString("title_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string watchtype_automatic_en {
            get {
                return ResourceManager.GetString("watchtype_automatic_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatique.
        /// </summary>
        public static string watchtype_automatic_fr {
            get {
                return ResourceManager.GetString("watchtype_automatic_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動捲き式.
        /// </summary>
        public static string watchtype_automatic_jp {
            get {
                return ResourceManager.GetString("watchtype_automatic_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动系列.
        /// </summary>
        public static string watchtype_automatic_sc {
            get {
                return ResourceManager.GetString("watchtype_automatic_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動系列.
        /// </summary>
        public static string watchtype_automatic_tc {
            get {
                return ResourceManager.GetString("watchtype_automatic_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartz.
        /// </summary>
        public static string watchtype_quartz_en {
            get {
                return ResourceManager.GetString("watchtype_quartz_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartz.
        /// </summary>
        public static string watchtype_quartz_fr {
            get {
                return ResourceManager.GetString("watchtype_quartz_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クオーツ.
        /// </summary>
        public static string watchtype_quartz_jp {
            get {
                return ResourceManager.GetString("watchtype_quartz_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 石英系列.
        /// </summary>
        public static string watchtype_quartz_sc {
            get {
                return ResourceManager.GetString("watchtype_quartz_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 石英系列.
        /// </summary>
        public static string watchtype_quartz_tc {
            get {
                return ResourceManager.GetString("watchtype_quartz_tc", resourceCulture);
            }
        }
    }
}
