//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErnestBorel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErnestBorel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string bc_home_en {
            get {
                return ResourceManager.GetString("bc_home_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string bc_home_fr {
            get {
                return ResourceManager.GetString("bc_home_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メインページ.
        /// </summary>
        public static string bc_home_jp {
            get {
                return ResourceManager.GetString("bc_home_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主页.
        /// </summary>
        public static string bc_home_sc {
            get {
                return ResourceManager.GetString("bc_home_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 依波路.
        /// </summary>
        public static string bc_home_tc {
            get {
                return ResourceManager.GetString("bc_home_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string bc_watch_en {
            get {
                return ResourceManager.GetString("bc_watch_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string bc_watch_fr {
            get {
                return ResourceManager.GetString("bc_watch_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シリーズ.
        /// </summary>
        public static string bc_watch_jp {
            get {
                return ResourceManager.GetString("bc_watch_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系列.
        /// </summary>
        public static string bc_watch_sc {
            get {
                return ResourceManager.GetString("bc_watch_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系列.
        /// </summary>
        public static string bc_watch_tc {
            get {
                return ResourceManager.GetString("bc_watch_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;CASUAL SERIES is a men’s collection of Ernest Borel celebrating the effortless versatility that gives everyday styling a suave and comfortable boost for urban gentlemen to flaunt their refined but nonchalant demeanour in every occasion from desk to dinner.&lt;/p&gt;.
        /// </summary>
        public static string casual_desc_en {
            get {
                return ResourceManager.GetString("casual_desc_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;CASUAL SERIES is a men’s collection of Ernest Borel celebrating the effortless versatility that gives everyday styling a suave and comfortable boost for urban gentlemen to flaunt their refined but nonchalant demeanour in every occasion from desk to dinner.&lt;/p&gt;.
        /// </summary>
        public static string casual_desc_fr {
            get {
                return ResourceManager.GetString("casual_desc_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;CASUAL SERIES is a men’s collection of Ernest Borel celebrating the effortless versatility that gives everyday styling a suave and comfortable boost for urban gentlemen to flaunt their refined but nonchalant demeanour in every occasion from desk to dinner.&lt;/p&gt;.
        /// </summary>
        public static string casual_desc_jp {
            get {
                return ResourceManager.GetString("casual_desc_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;CASUAL SERIES (潇洒雅仕) –– 是依波路男士腕表的产品线。&lt;/p&gt;&lt;p&gt;CASUAL SERIES意在带给都市人一枚任何场合都适合配戴、风格百搭而时尚舒适的腕表，散发出都市男士潇洒不羁的雅仕风范。  &lt;/p&gt;.
        /// </summary>
        public static string casual_desc_sc {
            get {
                return ResourceManager.GetString("casual_desc_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;CASUAL SERIES (瀟灑雅仕) –– 是依波路男士腕表的產品線。&lt;/p&gt;&lt;p&gt;CASUAL SERIES意在帶給都市人一枚任何場合都適合配戴、風格百搭而時尚舒適的腕表，散發出都市男士瀟灑不羈的雅仕風範。  &lt;/p&gt;.
        /// </summary>
        public static string casual_desc_tc {
            get {
                return ResourceManager.GetString("casual_desc_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance in Heart Since 1856. Ernest Borel –  founded in Neuchatel, Switzerland. Exquisitely elegant, admirably designed automatic and quartz-movement wrist watches for men and women..
        /// </summary>
        public static string collection_desc_all_en {
            get {
                return ResourceManager.GetString("collection_desc_all_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance in Heart Since 1856. Ernest Borel –  founded in Neuchatel, Switzerland. Exquisitely elegant, admirably designed automatic and quartz-movement wrist watches for men and women..
        /// </summary>
        public static string collection_desc_all_fr {
            get {
                return ResourceManager.GetString("collection_desc_all_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance in Heart Since 1856. Ernest Borel –  founded in Neuchatel, Switzerland. Exquisitely elegant, admirably designed automatic and quartz-movement wrist watches for men and women..
        /// </summary>
        public static string collection_desc_all_jp {
            get {
                return ResourceManager.GetString("collection_desc_all_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 瑞士手表品牌—依波路，推出最新高档手表产品包括自动系列和石英系列，分别为男士、女士分别打造不同品味的高档手表,情侣表等.
        /// </summary>
        public static string collection_desc_all_sc {
            get {
                return ResourceManager.GetString("collection_desc_all_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 源自1856年的浪漫經典 — 依波路，發源自「鐘表王國」瑞士紐察圖，以&apos;精益求精&apos;的探索精神，打造出款式設計典雅精致的奢華腕表。.
        /// </summary>
        public static string collection_desc_all_tc {
            get {
                return ResourceManager.GetString("collection_desc_all_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel {0} Collection : {1}.
        /// </summary>
        public static string collection_desc_type_en {
            get {
                return ResourceManager.GetString("collection_desc_type_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel {0} Collection : {1}.
        /// </summary>
        public static string collection_desc_type_fr {
            get {
                return ResourceManager.GetString("collection_desc_type_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - {0} : {1}.
        /// </summary>
        public static string collection_desc_type_jp {
            get {
                return ResourceManager.GetString("collection_desc_type_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 瑞士手表品牌依波路手表，推出最新{0}名牌手表包括{1}.
        /// </summary>
        public static string collection_desc_type_sc {
            get {
                return ResourceManager.GetString("collection_desc_type_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 瑞士手表品牌依波路手表，推出最新{0}名牌手表包括{1}.
        /// </summary>
        public static string collection_desc_type_tc {
            get {
                return ResourceManager.GetString("collection_desc_type_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - Watch Collections.
        /// </summary>
        public static string collection_title_all_en {
            get {
                return ResourceManager.GetString("collection_title_all_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - Watch Collections.
        /// </summary>
        public static string collection_title_all_fr {
            get {
                return ResourceManager.GetString("collection_title_all_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - 最新製品.
        /// </summary>
        public static string collection_title_all_jp {
            get {
                return ResourceManager.GetString("collection_title_all_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 依波路官方网站 - 依波路手表最新产品.
        /// </summary>
        public static string collection_title_all_sc {
            get {
                return ResourceManager.GetString("collection_title_all_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 依波路官方網站 - 依波路手表最新產品.
        /// </summary>
        public static string collection_title_all_tc {
            get {
                return ResourceManager.GetString("collection_title_all_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - Watch Collections - {0}.
        /// </summary>
        public static string collection_title_type_en {
            get {
                return ResourceManager.GetString("collection_title_type_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - Watch Collections - {0}.
        /// </summary>
        public static string collection_title_type_fr {
            get {
                return ResourceManager.GetString("collection_title_type_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - 最新製品 - {0}.
        /// </summary>
        public static string collection_title_type_jp {
            get {
                return ResourceManager.GetString("collection_title_type_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 依波路表官方网站 - 依波路{0}手表.
        /// </summary>
        public static string collection_title_type_sc {
            get {
                return ResourceManager.GetString("collection_title_type_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 依波路表官方網站 - 依波路{0}手表.
        /// </summary>
        public static string collection_title_type_tc {
            get {
                return ResourceManager.GetString("collection_title_type_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;ROMANTIC SERIES (浪漫情侣) –– 是依波路的情侣腕表产品线，寓意世间爱情都能穿越时空，以对表传情，方寸说爱。&lt;/p&gt;&lt;p&gt;承袭品牌过百年的浪漫优雅，ROMANTIC SERIES终在时间的淬炼下把一款款精致华美的情侣对表集结成群，流芳万世。&lt;/p&gt;.
        /// </summary>
        public static string couple_desc_en {
            get {
                return ResourceManager.GetString("couple_desc_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;ROMANTIC SERIES (浪漫情侣) –– 是依波路的情侣腕表产品线，寓意世间爱情都能穿越时空，以对表传情，方寸说爱。&lt;/p&gt;&lt;p&gt;承袭品牌过百年的浪漫优雅，ROMANTIC SERIES终在时间的淬炼下把一款款精致华美的情侣对表集结成群，流芳万世。&lt;/p&gt;.
        /// </summary>
        public static string couple_desc_fr {
            get {
                return ResourceManager.GetString("couple_desc_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;ROMANTIC SERIES (浪漫情侣) –– 是依波路的情侣腕表产品线，寓意世间爱情都能穿越时空，以对表传情，方寸说爱。&lt;/p&gt;&lt;p&gt;承袭品牌过百年的浪漫优雅，ROMANTIC SERIES终在时间的淬炼下把一款款精致华美的情侣对表集结成群，流芳万世。&lt;/p&gt;.
        /// </summary>
        public static string couple_desc_jp {
            get {
                return ResourceManager.GetString("couple_desc_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;ROMANTIC SERIES (浪漫情侣) –– 是依波路的情侣腕表产品线，寓意世间爱情都能穿越时空，以对表传情，方寸说爱。&lt;/p&gt;&lt;p&gt;承袭品牌过百年的浪漫优雅，ROMANTIC SERIES终在时间的淬炼下把一款款精致华美的情侣对表集结成群，流芳万世。&lt;/p&gt;.
        /// </summary>
        public static string couple_desc_sc {
            get {
                return ResourceManager.GetString("couple_desc_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;ROMANTIC SERIES (浪漫情侶) –– 是依波路的情侶腕表產品線，寓意世間愛情都能穿越時空，以對表傳情，方寸說愛。&lt;/p&gt;&lt;p&gt;承襲品牌過百年的浪漫優雅，ROMANTIC SERIES終在時間的淬煉下把一款款精緻華美的情侶對表集結成群，流芳萬世。&lt;/p&gt;.
        /// </summary>
        public static string couple_desc_tc {
            get {
                return ResourceManager.GetString("couple_desc_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount_en {
            get {
                return ResourceManager.GetString("Discount_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试算扣率.
        /// </summary>
        public static string Discount_sc {
            get {
                return ResourceManager.GetString("Discount_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 試算扣率.
        /// </summary>
        public static string Discount_tc {
            get {
                return ResourceManager.GetString("Discount_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounted Total.
        /// </summary>
        public static string DiscountTotal_en {
            get {
                return ResourceManager.GetString("DiscountTotal_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 折后总计.
        /// </summary>
        public static string DiscountTotal_sc {
            get {
                return ResourceManager.GetString("DiscountTotal_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 折後總計.
        /// </summary>
        public static string DiscountTotal_tc {
            get {
                return ResourceManager.GetString("DiscountTotal_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been received, order number: {0}.
        /// </summary>
        public static string emailsubject_en {
            get {
                return ResourceManager.GetString("emailsubject_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已收到你的订单，订单编号: {0}.
        /// </summary>
        public static string emailsubject_sc {
            get {
                return ResourceManager.GetString("emailsubject_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已收到你的訂單，訂單編號: {0}.
        /// </summary>
        public static string emailsubject_tc {
            get {
                return ResourceManager.GetString("emailsubject_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Gender_F_en {
            get {
                return ResourceManager.GetString("Gender_F_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 女装.
        /// </summary>
        public static string Gender_F_sc {
            get {
                return ResourceManager.GetString("Gender_F_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 女裝.
        /// </summary>
        public static string Gender_F_tc {
            get {
                return ResourceManager.GetString("Gender_F_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Gender_M_en {
            get {
                return ResourceManager.GetString("Gender_M_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 男装.
        /// </summary>
        public static string Gender_M_sc {
            get {
                return ResourceManager.GetString("Gender_M_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 男裝.
        /// </summary>
        public static string Gender_M_tc {
            get {
                return ResourceManager.GetString("Gender_M_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string Gender_N_en {
            get {
                return ResourceManager.GetString("Gender_N_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中装.
        /// </summary>
        public static string Gender_N_sc {
            get {
                return ResourceManager.GetString("Gender_N_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中裝.
        /// </summary>
        public static string Gender_N_tc {
            get {
                return ResourceManager.GetString("Gender_N_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;FEMININE SERIES (优雅淑女) –– 是依波路女士腕表的产品线。&lt;/p&gt;&lt;p&gt;意在透过多种唯美耀目的细节设计，把女性端庄高雅、时尚大方、清新脱俗、雍容华贵、朴素商务等万千风韵展现人前。&lt;/p&gt;.
        /// </summary>
        public static string lady_desc_en {
            get {
                return ResourceManager.GetString("lady_desc_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;FEMININE SERIES (优雅淑女) –– 是依波路女士腕表的产品线。&lt;/p&gt;&lt;p&gt;意在透过多种唯美耀目的细节设计，把女性端庄高雅、时尚大方、清新脱俗、雍容华贵、朴素商务等万千风韵展现人前。&lt;/p&gt;.
        /// </summary>
        public static string lady_desc_fr {
            get {
                return ResourceManager.GetString("lady_desc_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;FEMININE SERIES (优雅淑女) –– 是依波路女士腕表的产品线。&lt;/p&gt;&lt;p&gt;意在透过多种唯美耀目的细节设计，把女性端庄高雅、时尚大方、清新脱俗、雍容华贵、朴素商务等万千风韵展现人前。&lt;/p&gt;.
        /// </summary>
        public static string lady_desc_jp {
            get {
                return ResourceManager.GetString("lady_desc_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;FEMININE SERIES (优雅淑女) –– 是依波路女士腕表的产品线。&lt;/p&gt;&lt;p&gt;意在透过多种唯美耀目的细节设计，把女性端庄高雅、时尚大方、清新脱俗、雍容华贵、朴素商务等万千风韵展现人前。&lt;/p&gt;.
        /// </summary>
        public static string lady_desc_sc {
            get {
                return ResourceManager.GetString("lady_desc_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;FEMININE SERIES (優雅淑女) –– 是依波路女士腕表的產品線。&lt;/p&gt;&lt;p&gt;意在透過多種唯美耀目的細節設計，把女性端莊高雅、時尚大方、清新脫俗、雍容華貴、樸素商務等萬千風韻展現人前。&lt;/p&gt;.
        /// </summary>
        public static string lady_desc_tc {
            get {
                return ResourceManager.GetString("lady_desc_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string OrderNumber_en {
            get {
                return ResourceManager.GetString("OrderNumber_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单编号.
        /// </summary>
        public static string OrderNumber_sc {
            get {
                return ResourceManager.GetString("OrderNumber_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 訂單編號.
        /// </summary>
        public static string OrderNumber_tc {
            get {
                return ResourceManager.GetString("OrderNumber_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderSummary.
        /// </summary>
        public static string OrderSummary_en {
            get {
                return ResourceManager.GetString("OrderSummary_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单总结.
        /// </summary>
        public static string OrderSummary_sc {
            get {
                return ResourceManager.GetString("OrderSummary_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 訂單總結.
        /// </summary>
        public static string OrderSummary_tc {
            get {
                return ResourceManager.GetString("OrderSummary_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty_en {
            get {
                return ResourceManager.GetString("Qty_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量.
        /// </summary>
        public static string Qty_sc {
            get {
                return ResourceManager.GetString("Qty_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 數量.
        /// </summary>
        public static string Qty_tc {
            get {
                return ResourceManager.GetString("Qty_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 實際結算折扣以依波路與供應商簽署合同為準.
        /// </summary>
        public static string Reamark_tc {
            get {
                return ResourceManager.GetString("Reamark_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实际结算折扣以依波路舄供应商签署合同为准.
        /// </summary>
        public static string Remark_en {
            get {
                return ResourceManager.GetString("Remark_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实际结算折扣以依波路與供应商签署合同为准.
        /// </summary>
        public static string Remark_sc {
            get {
                return ResourceManager.GetString("Remark_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Subtotal_en {
            get {
                return ResourceManager.GetString("Subtotal_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小计.
        /// </summary>
        public static string Subtotal_sc {
            get {
                return ResourceManager.GetString("Subtotal_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小計.
        /// </summary>
        public static string Subtotal_tc {
            get {
                return ResourceManager.GetString("Subtotal_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - {0}.
        /// </summary>
        public static string title_en {
            get {
                return ResourceManager.GetString("title_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - {0}.
        /// </summary>
        public static string title_fr {
            get {
                return ResourceManager.GetString("title_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ernest Borel - {0}.
        /// </summary>
        public static string title_jp {
            get {
                return ResourceManager.GetString("title_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 瑞士依波路表官网 - {0}.
        /// </summary>
        public static string title_sc {
            get {
                return ResourceManager.GetString("title_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 瑞士依波路表官網 - {0}.
        /// </summary>
        public static string title_tc {
            get {
                return ResourceManager.GetString("title_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total_en {
            get {
                return ResourceManager.GetString("Total_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总计.
        /// </summary>
        public static string Total_sc {
            get {
                return ResourceManager.GetString("Total_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 總計.
        /// </summary>
        public static string Total_tc {
            get {
                return ResourceManager.GetString("Total_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total QTY.
        /// </summary>
        public static string TotalQty_en {
            get {
                return ResourceManager.GetString("TotalQty_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总数量.
        /// </summary>
        public static string TotalQty_sc {
            get {
                return ResourceManager.GetString("TotalQty_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 總數量.
        /// </summary>
        public static string TotalQty_tc {
            get {
                return ResourceManager.GetString("TotalQty_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitPrice.
        /// </summary>
        public static string UnitPrice_en {
            get {
                return ResourceManager.GetString("UnitPrice_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单价.
        /// </summary>
        public static string UnitPrice_sc {
            get {
                return ResourceManager.GetString("UnitPrice_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 單價.
        /// </summary>
        public static string UnitPrice_tc {
            get {
                return ResourceManager.GetString("UnitPrice_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual Series.
        /// </summary>
        public static string watchfamily_casual_en {
            get {
                return ResourceManager.GetString("watchfamily_casual_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual Series.
        /// </summary>
        public static string watchfamily_casual_fr {
            get {
                return ResourceManager.GetString("watchfamily_casual_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASUAL SERIES(カジュアルな紳士).
        /// </summary>
        public static string watchfamily_casual_jp {
            get {
                return ResourceManager.GetString("watchfamily_casual_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 瀟洒雅仕.
        /// </summary>
        public static string watchfamily_casual_sc {
            get {
                return ResourceManager.GetString("watchfamily_casual_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 瀟洒雅仕.
        /// </summary>
        public static string watchfamily_casual_tc {
            get {
                return ResourceManager.GetString("watchfamily_casual_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romantic Series.
        /// </summary>
        public static string watchfamily_couple_en {
            get {
                return ResourceManager.GetString("watchfamily_couple_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romantic Series.
        /// </summary>
        public static string watchfamily_couple_fr {
            get {
                return ResourceManager.GetString("watchfamily_couple_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROMANTIC SERIES(ロマンチックな恋人たち).
        /// </summary>
        public static string watchfamily_couple_jp {
            get {
                return ResourceManager.GetString("watchfamily_couple_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浪漫情侶.
        /// </summary>
        public static string watchfamily_couple_sc {
            get {
                return ResourceManager.GetString("watchfamily_couple_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浪漫情侶.
        /// </summary>
        public static string watchfamily_couple_tc {
            get {
                return ResourceManager.GetString("watchfamily_couple_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feminine Series.
        /// </summary>
        public static string watchfamily_lady_en {
            get {
                return ResourceManager.GetString("watchfamily_lady_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feminine Series.
        /// </summary>
        public static string watchfamily_lady_fr {
            get {
                return ResourceManager.GetString("watchfamily_lady_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEMININE SERIES (フェミニンな淑女).
        /// </summary>
        public static string watchfamily_lady_jp {
            get {
                return ResourceManager.GetString("watchfamily_lady_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 優雅淑女.
        /// </summary>
        public static string watchfamily_lady_sc {
            get {
                return ResourceManager.GetString("watchfamily_lady_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 優雅淑女.
        /// </summary>
        public static string watchfamily_lady_tc {
            get {
                return ResourceManager.GetString("watchfamily_lady_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string watchtype_automatic_en {
            get {
                return ResourceManager.GetString("watchtype_automatic_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatique.
        /// </summary>
        public static string watchtype_automatic_fr {
            get {
                return ResourceManager.GetString("watchtype_automatic_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動捲き式.
        /// </summary>
        public static string watchtype_automatic_jp {
            get {
                return ResourceManager.GetString("watchtype_automatic_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动机芯.
        /// </summary>
        public static string watchtype_automatic_sc {
            get {
                return ResourceManager.GetString("watchtype_automatic_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動機芯.
        /// </summary>
        public static string watchtype_automatic_tc {
            get {
                return ResourceManager.GetString("watchtype_automatic_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartz.
        /// </summary>
        public static string watchtype_quartz_en {
            get {
                return ResourceManager.GetString("watchtype_quartz_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartz.
        /// </summary>
        public static string watchtype_quartz_fr {
            get {
                return ResourceManager.GetString("watchtype_quartz_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クオーツ.
        /// </summary>
        public static string watchtype_quartz_jp {
            get {
                return ResourceManager.GetString("watchtype_quartz_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 石英机芯.
        /// </summary>
        public static string watchtype_quartz_sc {
            get {
                return ResourceManager.GetString("watchtype_quartz_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 石英機芯.
        /// </summary>
        public static string watchtype_quartz_tc {
            get {
                return ResourceManager.GetString("watchtype_quartz_tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Order.
        /// </summary>
        public static string YourOrder_en {
            get {
                return ResourceManager.GetString("YourOrder_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你的订单.
        /// </summary>
        public static string YourOrder_sc {
            get {
                return ResourceManager.GetString("YourOrder_sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你的訂單.
        /// </summary>
        public static string YourOrder_tc {
            get {
                return ResourceManager.GetString("YourOrder_tc", resourceCulture);
            }
        }
    }
}
