<footer>
    <div class="container align-middle">
        <p class="text-center">CONTACT US</p>
        <div class="row text-center">
            <address class="col-md-4">
                <span class="adr-title">Ernest Borel S.A. (Head Office)</span><br>
                <p class="adr-desc">
                    Rue des Perrières 8, Case postale 234,<br>
                    CH – 2340 Le Noirmont, Switzerland<br>
                    T: +41-32-926 1726<br>
                    E: info@ernestborel.ch<br>
                </p>
            </address>
            <address class="col-md-4">
                <span class="adr-title">Ernest Borel (Far East) Co., Ltd</span><br>
                <p class="adr-desc">
                    Units 1612-18, Level 16, Tower 1, Grand Century<br>
                    Place, 193 Prince Edward Road West, Mong Kok,<br>
                    Kowloon, Hong Kong<br>
                    T: (852) 3628 5511<br>
                    E: enquiry@ernestborel.ch<br>
                </p>
            </address>
            <address class="col-md-4">
                <span class="adr-title">Ernest Borel (Guangzhou) Co., Ltd</span><br>
                <p class="adr-desc">
                    Suite 701, Taikoo Hui Hower 1, 385 Tianhe Road,
                    <br> Tianhe District, Guangzhou 510620, China
                    <br> T: 400 830 3865 / 800 830 3865
                    <br>
                </p>
            </address>
        </div>
        <p class="text-center">FOLLOW US</p>
        <div class="social row justify-content-center">
            <div class="col-2 col-lg-auto"><a target="_blank" href="https://weibo.com/ernestborel?is_hot=1"><img class="cart-icon img-fluid" src="../images/0_footer_sina_icon.png"></a></div>
            <div class="col-2 col-lg-auto">
                <a target="_blank" href="javascript:void(0);" id="wechat">
                    <img class="cart-icon img-fluid" src="../images/0_footer_wechat_icon.png">
                    <span id="wechat-qrcode">
                        <img class="cart-icon img-fluid" src="../../images/sns_icon/wechat_qr_code.png">
                    </span>
                </a>
            </div>
            <div class="col-2 col-lg-auto"><a target="_blank" href="https://instagram.com/explore/tags/ernestborel/"><img class="cart-icon img-fluid" src="../images/0_footer_ig_icon.png"></a></div>
            <div class="col-2 col-lg-auto"><a target="_blank" href="https://twitter.com/hashtag/ernestborel"><img class="cart-icon img-fluid" src="../images/0_footer_tweet_icon.png"></a></div>
            <div class="col-2 col-lg-auto"><a target="_blank" href="https://www.facebook.com/ErnestBorelHK;"><img class="cart-icon img-fluid" src="../images/0_footer_fb_icon.png"></a></div>
        </div>
        <p class="copyright text-center">2018 &copy; Ernest Borel. All Rights Reserved.</p>
    </div>
</footer>
